### ISSUE TITLE
Pixelorama imported as SpriteFrames results in empty frames

### ISSUE THREAD

**Issue by ChiliEater** [nklbdev/godot-4-importality#27]
On the latest master branch of Godot the add-on currently works without errors. However, when I try to import a .pxo file as SpriteFrames it generates the object without the actual sprites:

![image](https://github.com/nklbdev/godot-4-importality/assets/32131318/4e0b2cfb-23a1-4af6-97f4-228942dc05f6)

Do you know if this is a regression your end? Any help is appreciated. If you want, I can also provide the .pxo file.

**Comment by nklbdev** [comment]
Hello! I also had this problem. I was very surprised. One of the latest Godot updates may have broken backwards compatibility.

But there is good news: in the latest DEV versions, the resource `PortableCompressedTexture[2|3]D` has been corrected. Therefore, we can use it from plugin code instead of saving a separated PNG file.
This is how I did it in the file [atlas_maker.gd](https://github.com/nklbdev/godot-4-importality/blob/fix_empty_frames/addons/nklbdev.importality/atlas_maker.gd).

Try to take the plugin version from the [fix_empty_frames](https://github.com/nklbdev/godot-4-importality/tree/fix_empty_frames) branch and tell me about the results.

The PNG images that the plugin creates next to the imported file are no longer needed. If they remain, you can try to remove them. This shouldn't affect anything. Now the texture in compressed form is saved directly inside the `SpriteFrames` resource.

**Comment by ChiliEater** [comment]
Sorry for the late reply. The fixes from the branch have been working fine for me. Thank you!
